### ISSUE TITLE
请问怎么实现自定义序列化

### ISSUE THREAD

**Issue by myml** [go-macaron/pongo2#5]
fmt.Print打印的时候会默认调用String,
json序列号的时候会调用) MarshalJSON ,
请问pongo2显示变量的时候调用的什么函数?

**Comment by Unknwon** [comment]
显示变量是指？。。这个应该可能要去问 https://github.com/flosch/pongo2 了吧。。我还真没试过。。

**Comment by myml** [comment]
无闻大神好啊.我再看看,看源代码,调来跳去看不懂了...

**Comment by Unknwon** [comment]
我估计八成用的都是 https://github.com/flosch/pongo2/blob/master/value.go#L24。。。

**Comment by myml** [comment]
好像是,我还不会反射,试着用了一下,一样的输出.请问这个有办法自己定义吗

**Comment by Unknwon** [comment]
这个应该不行，所以需要你在传递到模板的就是 string 类型，也就是赋值之前你用自己的函数处理以下

**Comment by myml** [comment]
恩,明白了,看了只能用模板函数了,谢谢

**Comment by Unknwon** [comment]
客气~
