### ISSUE TITLE
pongo2支持自定义{{}}吗？

### ISSUE THREAD

**Issue by myml** [go-macaron/pongo2#6]
像学习一下AngularJs，和pongo的变量定义{{}}有冲突，标准模板好像可以设置这个，pongo2可以吗
睡觉了，明天再来

**Comment by Unknwon** [comment]
我记得好像不行。。

**Comment by Unknwon** [comment]
晚安。。。

**Comment by myml** [comment]
明白了,好像angularJs也不需要写模板了,直接做接口就行

**Comment by Unknwon** [comment]
恩是，基本上就是go只做API层
