### ISSUE TITLE
Does not work with bindata

### ISSUE THREAD

**Issue by lordnynex** [go-macaron/pongo2#7]
Unable to start the application when bindata is in use. 

It looks like it's reading all files in the in the tree and trying to read them incorrectly somehow. 

This same code/options works if I use `macaron.Renderer`

```
2016/03/27 23:29:39 "templates/test": [Error (where: fromfile) in templates/test.tmpl] open templates/test.tmpl: no such file or directory
```

**Comment by Unknwon** [comment]
Yes, Pongo2 v3 does not allow in-memory file system.
